### ISSUE TITLE
model duplicate attribute issues [ migrated from xml-database ] 

### ISSUE THREAD

**Issue by jsfenfen** [jsfenfen/990-xml-metadata#2]
In return.models:
pf_part_vi has two attributes named AppldTESTxAmt that refer to Part VI Line 6c and Part VI Line 11 of the PF respectively.
SkdASpprtdOrgInfrmtn has two attributes named EIN that refer to filer EIN and Part I Line 12g Column (supported org EIN).
I suspect this is actually an issue with the 990 concordance file / variables sheet as the duplicate issue can be found there as well. I wasn't able to get the default models to migrate to MySQL until I changed db_name for one of the two duplicated fields in the variables.csv file that IRSX uses and the corresponding attribute in return.models. The parser runs fine after the fix - I was mostly curious whether you'd encountered this and how you'd addressed it if you had.
(also thanks for this thing it's amazing)

**Comment by jsfenfen** [comment]
It seems like this is probably a case sensitivity issue. This hasn't been a problem on postgres, but I believe mysql handles differently. There should be a solution.
 
Here are the var names and the original xpaths--note that these refer to totally different variables. The xpaths are identical *except* for capitalization. I believe this is "fixed" in the 2017 schemas so the names are more different. But I think this needs a manual fix for the years where we get collisions in case-insensitive contexts. 

AppldTESTxAmt | /IRS990PF/ExciseTaxBasedOnInvstIncmGrp/AppliedToESTaxAmt
AppldTEsTxAmt | /IRS990PF/ExciseTaxBasedOnInvstIncmGrp/AppliedToEsTaxAmt

**Comment by styloooo** [comment]
So, is this issue more complicated than applying revised `db_name`s? I've got a version of `variables.csv` without duplicate field names I can send over. I'd like to use this repo as a submodule on some infrastructure I'm building around our 990 db but I'm concerned about our current field names differing from the upstream docs. Of course, I could always just write some band-aid code for the time being.

**Comment by jsfenfen** [comment]
Hey @thirawr , send your fix over, simplest thing is to use that. There are a few other minor changes I've been meaning to add as well.

**Comment by styloooo** [comment]
Here it is:
[variables-unduped.csv.zip](https://github.com/jsfenfen/990-xml-metadata/files/2081148/variables-unduped.csv.zip)

`/IRS990PF/ExciseTaxBasedOnInvstIncmGrp/AppliedToESTaxAmt` was renamed to `AmtCrdtNxtYr` from `AppldTESTxAmt`


`/IRS990ScheduleA/SupportedOrgInformationGrp/EIN` was renamed to `SpprtdOrgEIN` from `EIN`

**Comment by jsfenfen** [comment]
Thx @thirawr. Rereading I think I removed the dupes already actually, but I can take yr fix for appliedtotestaxamt. I assume ein has the same name-collision-in-MySQL issue.
